name: "master"

on:
  push:
    branches:
      - "master"
      - "feature/*"
    tags:
      - "*"
  pull_request:
    branches:
      - "master"
      - "feature/*"
    tags:
      - "*"

jobs:
  job_windows:
    name: "Build for Windows"
    runs-on: 'windows-latest'
    steps:
      - name: "Git Clone"
        uses: "actions/checkout@v2"
      - name: "Setup JDK"
        uses: "actions/setup-java@v1"
        with:
          java-version: "21"
          architecture: "x64"
      - name: "Gradle Windows"
        shell: cmd
        run: |
          gradlew.bat buildWindows
      - name: "Upload Windows build"
        uses: "actions/upload-artifact@v4"
        with:
          name: "windows"
          path: "build/distributions/foldershow.zip"

  job_mac:
    name: "Build for Mac"
    runs-on: 'macos-latest'
    steps:
      - name: "Git Clone"
        uses: "actions/checkout@v2"
      - name: "Setup JDK"
        uses: "actions/setup-java@v1"
        with:
          java-version: "21"
          architecture: "x64"
      - name: "Gradle Mac"
        run: |
          chmod +x ./gradlew
          ./gradlew buildMac
      - name: "Upload Mac build"
        uses: "actions/upload-artifact@v4"
        with:
          name: "mac"
          path: "build/distributions/foldershow.tar.gz"

  job_linux:
    name: "Build for Linux"
    runs-on: 'ubuntu-latest'
    steps:
      - name: "Git Clone"
        uses: "actions/checkout@v2"
      - name: "Setup JDK"
        uses: "actions/setup-java@v1"
        with:
          java-version: "21"
          architecture: "x64"
      - name: "Gradle Linux"
        run: |
          chmod +x ./gradlew
          ./gradlew buildLinux
      - name: "Upload Linux build"
        uses: "actions/upload-artifact@v4"
        with:
          name: "linux"
          path: "build/distributions/foldershow.tar.gz"

  job_release:
    name: "Release"
    needs:
      - job_windows
      - job_mac
      - job_linux
    runs-on: 'ubuntu-latest'
    if: "contains(github.ref, 'tags/')"
    steps:
      - name: "Download all build"
        uses: "actions/download-artifact@v4"
        with:
          path: "build"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/windows/foldershow.zip
            build/mac/foldershow.tar.gz
            build/linux/foldershow.tar.gz
